#!/bin/bash
function showRestNotification()
{
  if [[ "$OSTYPE" == "linux-gnu" ]]; then
      notify-send "Insomnia" "Time to take a rest"  -u critical -t 5000

  elif [[ "$OSTYPE" == "darwin"* ]]; then
          terminal-notifier -title "Insomnia" -message "It's time to take a rest" -sound "default" -group rest -timeout 10 -appIcon sleep.png -closeLabel Dismiss
  fi
}

declare -a sleepTimes



showRestNotification
