#!/bin/bash
#sandman-lite
#An application that will remind you when to go to bed based on your
#wake up time and the optimal sleep times algorithm.
#Version 1.0.0

date () {
    case "$OSTYPE" in
      darwin*) command gdate "$@" ;;
      linux*)  command date  "$@" ;;
      *) printf 'Unsupported OS type: %s\n' "$OSTYPE" >&2
         exit 1 ;;
     esac
}

function help()
{
  echo "NAME: sandman-lite"
  echo "Usage: "
  echo "    [-t] (tests notification)"
  echo "    [-s wakeUpTime] wakeuptime 24 hour time zeros necessary ex. 08:05 (sets new wakeuptime)"
  echo "    [-g] (gets pending notifications)"
  echo "    [-h] (brings up the help page)"
  echo "    [-v] (prints out version of sandman-lite)"
}

function showRestNotification()
{
  if [[ "$OSTYPE" == "linux-gnu" ]]; then
      notify-send "Sandman" "Time to take a rest"  -u critical -t 7000 -i /usr/local/sbin/sleep.png

  elif [[ "$OSTYPE" == "darwin"* ]]; then
      terminal-notifier -title "Sandman" -message "Time to take a rest"  -sound "default"  -group rest -timeout 7  -appIcon /usr/local/sbin/sleep.png
  fi
}
function generateSleepTimes()
{

  oldIFS=$IFS
  IFS=: splitTime=(${wakeUpTime##*-})
  wakeUpHours=${splitTime[0]}
  wakeUpMinutes=${splitTime[1]}
  currentHours=$(date +'%H')
  currentMinutes=$(date +'%M')



  if [[ $wakeUpHours < $currentHours ]]; then
        IFS=$oldIFS
        wakeUpTime="$wakeUpTime tomorrow"

  elif [[ "$wakeUpHours" == "$currentHours" && $wakeUpMinutes < $currentMinutes ]]; then
        IFS=$oldIFS
        wakeUpTime="$wakeUpTime tomorrow"

  else
        IFS=$oldIFS

        wakeUpTime="$wakeUpTime today"

  fi
      tempTime=$(date -d "$wakeUpTime - 15 minutes" +"%D %H:%M")
      sleepTimes[6]=$(date -d "$tempTime" +"%D %H:%M")



  for i in {5..0}
  do
      sleepTimes[$i]=$(date -d "${sleepTimes[$i+1]} - 1 hour 30 minutes" +"%D %H:%M")
  done


  for i in {5..0}
  do
      secondTimes[$i]=$(date -d "${sleepTimes[$i]}" +"%s")
      sleepTimes[$i]=$(date -d "${sleepTimes[$i]}" +"%Y%m%d%H%M")
  done
}

function removeNotificatonJobs()
{
  for i in `atq | awk '{print $1}'`;do atrm $i;done
  echo "Old Notifications removed"
}

function setUpNotificationJobs()
{
  removeNotificatonJobs
  for i in {0..5}
  do
    if [[ $(date -d now +"%s") -le ${secondTimes[$i]} ]]; then
      at -f /usr/local/sbin/noti.sh -t ${sleepTimes[$i]} 2> /dev/null
    fi
  done
  echo "New Notifications set"
}


if [[ $# == 0 ]]; then
  help
  exit 0
fi

function getSleepTimes()
{
  atq
}

while getopts ":vrghts::" opt; do
  case $opt in
    s)
      if [[ $# -gt 2 ]]; then
        echo "Option -s only accepts one argument" <&2
        exit 1
      fi
      wakeUpTime=$OPTARG
      generateSleepTimes
      setUpNotificationJobs
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    t)
      echo "Testing rest notification"
      showRestNotification
    ;;
    h)
      help
    ;;
    g)
      getSleepTimes
    ;;
    r)
      removeNotificatonJobs
    ;;
    v)
      echo "Version 1.0.0"
    ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done
